var arrLang = {
    'en': {
        'title': 'Lycoon | Official website',
        'projects': 'Projects',
        'faq': 'FAQ',
        'contact': 'Contact',
        'language': 'Language',
        'welcome': 'Welcome',
        'movie': 'Movie enthusiast',
        'programmer': 'Computer engineering student',
        'jack-trades': 'Jack-of-all-trades',
        'videos': 'Videos',
        'video-desc': 'I love cinema, and that\'s why I love even more directing my own movies. Because of the budget a real shooting takes, I do them on Minecraft. That\'s called a machinima, a video made within a game.',
        'btn-videos': 'See my videos',
        'code': 'Code',
        'code-desc': 'As any form of art, programming is no exception. Being able to give life to something with a few lines of code is very exciting. It\'s not for nothing that I decided to make a career out of it.',
        'btn-code': 'See my code projects',
        'maps': 'Minecraft maps',
        'maps-desc': 'Minecraft is my favorite game. It\'s the game I\'ve ever dreamt of. Nearly everything can be made possible thanks to it. That\'s why besides making movies and coding mods out of it, I build maps.',
        'btn-maps': 'See my Minecraft maps',
        'faq-q1': 'How old are you?',
        'faq-r1': 'I\'m ' + diffYears + ' years old.',
        'faq-q2': 'Where are you from?',
        'faq-r2': 'I was born in Nancy, a beautiful city in the East of France. Nowadays, I live and study in Paris.',
        'faq-q3': 'What do you use to code?',
        'faq-r3': 'I enjoy a lot VSCode, which keeps everything simple and fast, and which allows you to custom nearly everthing. For Java though, I still like using Eclipse (maybe because I\'ve always used it).',
        'faq-q4': 'What languages do you speak?',
        'faq-r4': 'I speak French, Polish, English and Spanish. But also Python, Java, C#, OCaml, Rust, and C. I\'m okay at web development with HTML, CSS and Javascript.',
        'faq-q5': 'What\'s your favorite programming language?',
        'faq-r5': 'Rust. It is a promising language, very comfy to use. I really appreciate it as I feel like coding with a high-level language, for low-level programming. I guess this makes of Rust my favorite language as its syntax and features are close to perfection.',
        'faq-q6': 'How did you make this website?',
        'faq-r6': 'I use Bootstrap and the theme Lux. There is also some custom code I made in Javascript, CSS and PHP.',
        'contact-success': 'Your message has been sent successfully.',
        'contact-fail': 'The message could not be sent. An error has occurred.',
        'email': 'Email',
        'name': 'Name',
        'reason': 'Reason',
        'partnership': 'Partnership',
        'question': 'Question',
        'other': 'Other',
        'message': 'Message',
        'message-notice': 'If you want your request to be processed faster, be as concise as possible.',
        'send': 'Send'
    },
    'fr': {
        'title': "Lycoon | Site officiel",
        'projects': 'Projets',
        'faq': 'FAQ',
        'contact': "Contact",
        'language': "Langue",
        'welcome': 'Bienvenue',
        'movie': 'Passionné de cinéma',
        'programmer': 'Étudiant en ingénierie informatique',
        'jack-trades': 'Touche-à-tout',
        'videos': 'Vidéos',
        'video-desc': 'Je suis passionné par le cinéma, et c\'est pour ça que j\'aime encore plus réaliser des films que les regarder. Les coûts de tournage étant trop élevés dans la vie réelle, je les réalise sur Minecraft. C\'est ce que l\'on appelle un machinima, une vidéo réalisée dans un jeu.',
        'btn-videos': 'Voir mes vidéos',
        'code': 'Code',
        'code-desc': 'Comme n\'importe quelle forme d\'art, la programmation n\'y échappe pas. Pouvoir donner vie à un peu près n\'importe quoi avec de simples lignes de code est très excitant. Ce n\'est pas pour rien que j\'ai décidé d\'en faire mon futur métier.',
        'btn-code': 'Voir mes projets de code',
        'maps': 'Maps Minecraft',
        'maps-desc': 'Minecraft est mon jeu préféré. C\'est le jeu dont j\'ai toujours rêvé. Presque tout est rendu possible grâce à ce jeu. C\'est pour ça qu\'en plus de faire des vidéos et des mods avec, je construis des maps.',
        'btn-maps': 'Voir mes maps Minecraft',
        'faq-q1': 'Quel âge as-tu ?',
        'faq-r1': 'J\'ai ' + diffYears + ' ans.',
        'faq-q2': 'D\'où viens-tu ?',
        'faq-r2': 'Je suis né à Nancy, une magnifique ville de l\'Est de la France. Aujourd\'hui je vis et habite à Paris.',
        'faq-q3': 'Quels logiciels utilises-tu pour programmer ?',
        'faq-r3': 'J\'aime beaucoup VSCode, tout y est simple et rapide. On peut personnaliser à peu près tout, ce qui permet d\'être très efficace. En Java par contre, j\'utilise Eclipse (sûrement parce que je l\'ai toujours utilisé).',
        'faq-q4': 'Quelles langues parles-tu ?',
        'faq-r4': 'Je parle français, polonais, anglais et espagnol. Mais aussi le Python, Java, C#, OCaml, Rust, et le C. Je me débrouille en développement web avec le HTML, CSS et le Javascript.',
        'faq-q5': 'Quel est ton langage de programmation préféré ?',
        'faq-r5': 'Rust. C\'est un langage très prometteur, super pratique à utiliser. Je l\'aime beaucoup car il donne l\'impression d\'écrire dans un langage haut niveau alors qu\'il est bas niveau. Sa syntaxe et ses fonctionnalités sont proches de la perfection tellement il rassemble les qualités et oublie les défauts des autres langages.',
        'faq-q6': 'Comment as-tu fait le site ?',
        'faq-r6': 'J\'utilise le thème Lux de Bootstrap. Il y a aussi un peu de code de moi en Javascript, CSS et PHP.',
        'contact-success': 'Le message a été envoyé avec succès.',
        'contact-fail': 'Le message n\'a pas pu être envoyé. Une erreur est survenue.',
        'email': 'Email',
        'name': 'Nom',
        'reason': 'Objet',
        'partnership': 'Partenariat',
        'question': 'Question',
        'other': 'Autre',
        'message': 'Message',
        'message-notice': 'Si vous voulez que votre message soit traité rapidement, soyez le plus concis possible.',
        'send': 'Envoyer'
    }
};